config/routes.rb
Ovec::Application.routes.draw do

  resources :projects do 
     resources :pictures
  end

  resources :activities

  devise_for :admins
  get "pages/home"

  root 'pages#home'

	match 'contact' => 'contact#new', :via => :get
	match 'contact' => 'contact#create', :via => :post
end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :pictures

	validates :title, presence: true
	validates :place, presence: true
	validates :description, presence: true

	has_attached_file :image, styles: { medium: "320x240#"}
	validates_attachment :image, presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 5.megabytes }

  validate :showcase_boolean_limit

  protected

  def showcase_boolean_limit
  	if Project.where(:showcase => true).count > 3
  	errors.add :showcase, "Je kan maar 3 projecten uitlichten, verwijder eerst het vinkje bij het te verwijderen project."
		end
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, except: [:index, :show]
  # GET /projects
  # GET /projects.json
  def index
    @project_groups = Project.all.in_groups_of(3, false)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :place, :description, :image, :showcase)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size %>
  <%= f.full_error :image_content_type %>

  <%= f.input :image, label: 'Voeg afbeelding toe' %>
  <%= f.input :title, label: 'Titel' %>
  <%= f.input :place, label: 'Plaats' %>
  <%= f.input :description, label: 'Omschrijving' %>
  <%= f.input :showcase, label: 'Laat zien in uitgelichte projecten' %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<br><br><br><br><br>
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<br><br>

<%= render 'layouts/showcase_projects' %><br>

<div id="blog">
  <div class="container">
    <div class="section_header">
      <h3>Overige projecten</h3>
    </div>
    <% @project_groups.each do |projects| %>
      <div class="row post_row">
        <% projects.each_with_index do |project, i| %>
          <div class="span4 post <%= check_for_last_class(i) %>">
            <div class="img">            
              <%= link_to (image_tag project.image(:medium)), project_pictures_path(project) %>
            </div>
            <div class="text">
              <span class="date">Datum toegevoegd: <%= project.created_at.to_s(:short) %></span>
              <p><strong> Titel </strong> <%= project.title %><br></p>
              <p><strong> Plaats </strong><%= project.place %><br><br></p>
              <p><%= truncate(project.description, length: 130) %></p>
            </div>
            <% if admin_signed_in? %>
              <div class="author_box">  
                  <%= link_to 'Show', project_path(project) %>
                  <%= link_to 'Edit', edit_project_path(project) %>
                  <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <%= link_to 'New picture', new_project_picture_path(project) %> 
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<% if admin_signed_in? %>
  <%= link_to 'Voeg nieuw Project toe', new_project_path %>
<% end %>

app/views/projects/new.html.erb
<br><br><br><br><br>
<h1>Nieuw project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<br><br><br><br><br>
<p id="notice"><%= notice %></p>

<%= image_tag @project.image %>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Place:</strong>
  <%= @project.place %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<% if admin_signed_in? %>
	<%= link_to 'New picture', new_project_picture_path(@project) %> |
	<%= link_to 'Edit', edit_project_path(@project) %> |
	<%= link_to 'Back', projects_path %>
<% end %>