config/routes.rb
Ovec::Application.routes.draw do

  resources :projects do 
     resources :pictures
  end

  resources :activities

  devise_for :admins
  get "pages/home"

  root 'pages#home'

	match 'contact' => 'contact#new', :via => :get
	match 'contact' => 'contact#create', :via => :post
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :project

	has_attached_file :image, styles: { medium: "320x240#"}
  	validates_attachment :image, presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 5.megabytes }

    validates :title, presence: true
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :get_project
  before_filter :authenticate_admin!, except: [:index, :show]
  # GET /pictures
  # GET /pictures.json
  def index
    @picture_groups = @project.pictures.in_groups_of(3, false)
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = @project.pictures.find(params[:id])
  end

  # GET /pictures/new
  def new
    @project = Project.find(params[:project_id])
    @picture = @project.pictures.build
  end

  # GET /pictures/1/edit
  def edit
    @picture = @project.pictures.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = @project.pictures.build(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to project_pictures_url(@project), notice: 'Picture was successfully created.' }
        format.json { render action: 'show', status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    @picture = @project.pictures.find(params[:id])

    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to project_pictures_url(@project), notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = @project.pictures.find(params[:id])
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to (project_pictures_path(@project)) }
      format.json { head :no_content }
    end
  end

  private

    def get_project
      @project = Project.find(params[:project_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :project_id, :image)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= simple_form_for([@project, @picture]) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size %>
  <%= f.full_error :image_content_type %>

  <% if @project %>
    <p>Deze foto wordt toegevoegd aan: <%= @project.title %></p>
    <input type="hidden" name="picture[project_id]" value="<%= @project.id %>" />
  <% end %>

  <div class="inputs">
    <%= f.input :image, label: 'Voeg afbeelding toe' %>
    <%= f.input :title, label: 'Voeg een omschrijving van de foto toe' %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<br><br><br><br><br>
<h1>Foto aanpassen</h1>

<%= render 'form' %>

<%= link_to 'Back', project_pictures_path(@project) %>

app/views/pictures/index.html.erb
<br><br><br>

<% if !@project.pictures.empty? %>

<div id="blog">
  <div class="container">
    <div class="section_header">
      <h3>Foto's voor <%= @project.title %></h3>
    </div>
    <% @picture_groups.each do |pictures| %>
      <div class="row post_row">
        <% pictures.each_with_index do |picture, i| %>
          <div class="span4 post <%= check_for_last_class(i) %>">
            <div class="img">
              <%= link_to (image_tag picture.image(:medium)), [@project, picture] %>
            </div>
            <div class="text">
              <span class="date">Datum toegevoegd: <%= picture.created_at.to_s(:short) %></span>
              <p><strong> Omschrijving: </strong> <%= picture.title %></p>
            </div>  
            <% if admin_signed_in? %>
              <div class="author_box">   
                <p> 
                  <%= link_to 'Show', [@project, picture] %>
                  <%= link_to 'Edit', edit_project_picture_path(@project, picture) %>
                  <%= link_to 'Destroy', [@project, picture], :confirm => 'Are you sure?',
                  :method => :delete %>
                </p>
              </div>
            <% end %>
          </div>  
        <% end %>    
      </div>
    <% end %>
  </div>
</div>

<% else %>
  <br><br><br>
  <div class="section_header">
      <h3>Foto's voor <%= @project.title %></h3>
    </div>
  <div class="container">
    <p>Dit project heeft nog geen foto's.</p>
  </div>
<% end %>

<br>
<% if admin_signed_in? %>
  <p>
    <%= link_to 'New picture', new_project_picture_path(@project) %> |
    <%= link_to 'Back', @project %>
  </p>
<% end %>

app/views/pictures/new.html.erb
<br><br><br><br><br>
<h1>Nieuwe foto's voor <%= @project.title %></h1>

<%= render 'form' %>

<%= link_to 'Back', project_pictures_path(@project) %>

app/views/pictures/show.html.erb
<br><br><br><br><br>
<p id="notice"><%= notice %></p>

<%= image_tag @picture.image %>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Project:</strong>
  <%= @picture.project_id %>
</p>

<% if admin_signed_in? %>
	<%= link_to 'Edit', edit_project_picture_path(@project, @picture) %>
	<%= link_to 'Back', project_pictures_path(@project) %>
<% end %>