config/routes.rb
Ovec::Application.routes.draw do

  resources :projects do 
     resources :pictures
  end

  resources :activities

  devise_for :admins
  get "pages/home"

  root 'pages#home'

	match 'contact' => 'contact#new', :via => :get
	match 'contact' => 'contact#create', :via => :post
end

app/views/layouts/_features.html.erb
    <div id="features">
        <div class="container">
            <div class="section_header">
                <h3>Features</h3>
            </div> 
            <div class="row feature">
                <div class="span6">
                    <%= image_tag "showcase1.png" %>
                </div>
                <div class="span6 info">
                    <h3>
                        <%= image_tag "features-ico1.png" %>
                        Beautiful on all devices
                    </h3>
                    <p>
                        There are many variations of passages of Lorem Ipsum available, but the randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.
                    </p>
                </div>
            </div>
            <div class="row feature ss">
                <div class="span6 info">
                    <h3>
                        <%= image_tag "features-ico2.png" %>
                        Blog page included
                    </h3>
                    <p>
                        There are many variations of passages of Lorem Ipsum available, but the randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.
                    </p>
                </div>
                <div class="span6">
                    <%= image_tag "showcase2.png", class: "pull-right" %>
                </div>
            </div>
            <div class="row feature ss">
                <div class="span6">
                    <%= image_tag "showcase3.png" %>
                </div>
                <div class="span6 info">
                    <h3>
                        <%= image_tag "features-ico3.png" %>
                        Simple and clean coming soon page
                    </h3>
                    <p>
                        There are many variations of passages of Lorem Ipsum available, but the randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.
                    </p>
                </div>
            </div>
        </div>
    </div>

app/views/layouts/_footer.html.erb
<!-- starts footer -->
<footer id="footer">
  <div class="container">
    <div class="row sections">
  
      <div class="row credits">
        <div class="span12">
          <div class="row copyright">
            <div class="span12">
              Ovec Multiservice B.V. | <a class="text" href="mailto:info@ovec-multiservice.nl">info@ovec-multiservice.nl</a> | 020-6118506
            </div>
            <div class="span12">
                © 2013 All rights reserved.
            </div>
            <div class="span12">
                <% if admin_signed_in? %>
                    <%= link_to "Admin Logout", destroy_admin_session_path, method: :delete %>
                <% else %>
                    <%= link_to 'Admin sign in', new_admin_session_path %>
                <% end %>
            </div>
          </div>
        </div>            
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_homepagebanner.html.erb
    <section id="feature_slider" class="">
        <!-- 
            Each slide is composed by <img> and .info
            - .info's position is customized with css in index.css
            - each <img> parallax effect is declared by the following params inside its class:
            
            example: class="asset left-472 sp600 t120 z3"
            left-472 means left: -472px from the center
            sp600 is speed transition
            t120 is top to 120px
            z3 is z-index to 3
            Note: Maintain this order of params

            For the backgrounds, you can combine from the bgs folder :D
        -->
        <article class="slide" id="showcasing" class="frontpage-image1">
            <div class="info">
                <h2>Welkom op de website van Ovec-Multiservice b.v.</h2>
            </div>
        </article>
        <article class="slide" id="ideas" class="frontpage-image2">
            <div class="info">
                <h2>Voor al uw staal- en las-werken.</h2>
            </div>
            <!--
            <%= image_tag "slides/scene2/left.png", class: "asset left-480 sp600 t260 z1" %>
            <%= image_tag "slides/scene2/middle.png", class: "asset left-210 sp600 t213 z2" %>
            <%= image_tag "slides/scene2/right.png", class: "asset left60 sp600 t260 z1"  %>
            -->
        </article>
        <article class="slide" id="tour" class="frontpage-image3">
            <!--
            <%= image_tag "slides/scene3/ipad.png", class:  "asset left-472 sp650 t210 z3" %>
            <%= image_tag "slides/scene3/iphone.png", class: "asset left-365 sp600 t270 z4" %>
            <%= image_tag "slides/scene3/desktop.png", class: "asset left-350 sp450 t135 z2" %>
            <%= image_tag "slides/scene3/macbook.png", class: "asset left-185 sp550 t220 z1" %>
            -->
            <div class="info">
                <h2>Op het land of in het water.</h2>
                <!-- <a href="features.html">TOUR THE PRODUCT</a> -->
            </div>
        </article>
        <article class="slide" id="responsive" class="frontpage-image4">
            <!--
            <%= image_tag "slides/scene4/logo_ovec.TIFF", class: "asset left-472 sp600 t120 z3" %>
                <div class="info">
                <h2>
                    Responsive <strong>HTML5 & CSS3</strong>
                    Theme
                </h2>                
                </div>
                -->
        </article>        
    </section>

app/views/layouts/_navbar.html.erb
<div class="navbar <%= add_transparant_to_navbar %> navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/">
                <strong>OVEC-Multiservice b.v.</strong>
            </a>
            <div class="nav-collapse collapse">
                <ul class="nav pull-right">
                    <li><%= link_to 'Home', root_path %></li>
                    <li><%= link_to 'Activiteiten', activities_path %></li>
                    <li><%= link_to 'Projecten', projects_path %></li>
                    <li><%= link_to 'Contact', contact_path %></li>
                    
                    <!-- <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            PAGES
                            <b class="caret"></b>
                        </a>
                          <ul class="dropdown-menu">
                              <li><a href="features.html">Features</a></li>
                              <li><a href="services.html">Services</a></li>
                              <li><a href="portfolio.html">Portfolio</a></li>
                              <li><a href="portfolio-item.html">Portfolio Item</a></li>
                              <li><a href="coming-soon.html">Coming Soon</a></li>
                              <li><a href="sign-in.html">Sign in</a></li>
                              <li><a href="sign-up.html">Sign up</a></li>
                              <li><a href="backgrounds.html">Backgrounds</a></li>
                          </ul>
                        -->
                    </li>
                </ul>
            </div>
        </div>
      </div>
    </div>

app/views/layouts/_pricing.html.erb
<!-- Pricing Option -->
<div id="in_pricing">
    <div class="container">
        <div class="section_header">
            <h3>Pricing</h3>
        </div>

        <div class="row charts_wrapp">
            <!-- Plan Box -->
            <div class="span4">
                <div class="plan">
                    <div class="wrapper">
                        <h3>Lite</h3>
                        <div class="price">
                            <span class="dollar">$</span> 
                            <span class="qty">35</span> 
                            <span class="month">/month</span>
                        </div>
                        <div class="features">
                            <p>
                                <strong>10</strong>
                                Shared Projects
                            </p>
                            <p>
                                <strong>4</strong>
                                Team Members
                            </p>
                            <p>
                                <strong>10</strong>
                                Storage
                            </p>
                        </div>
                        <a class="order" href="pricing.html">ORDER NOW</a>
                    </div>
                </div>
            </div>
            <!-- Plan Box -->
            <div class="span4 pro">
                <div class="plan">
                    <div class="wrapper">
                        <%= image_tag "badge.png", class: "ribbon" %>
                        <h3>Pro</h3>
                        <div class="price">
                            <span class="dollar">$</span> 
                            <span class="qty">99</span> 
                            <span class="month">/month</span>
                        </div>
                        <div class="features">
                            <p>
                                <strong>10</strong>
                                Shared Projects
                            </p>
                            <p>
                                <strong>25</strong>
                                Team Members
                            </p>
                            <p>
                                <strong>Unlimited</strong>
                                 Storage
                            </p>
                            <p>
                                <strong>Plus </strong>
                                Phone Support
                            </p>
                        </div>
                        <a class="order" href="pricing.html">ORDER NOW</a>
                    </div>
                </div>
            </div>
            <!-- Plan Box -->
            <div class="span4 standar">
                <div class="plan">
                    <div class="wrapper">
                        <h3>Standard</h3>
                        <div class="price">
                            <span class="dollar">$</span> 
                            <span class="qty">65</span> 
                            <span class="month">/month</span>
                        </div>
                        <div class="features">
                            <p>
                                <strong>10</strong>
                                Shared Projects
                            </p>
                            <p>
                                <strong>4</strong>
                                Team Members
                            </p>
                            <p>
                                <strong>10</strong>
                                Storage
                            </p>
                        </div>
                        <a class="order" href="pricing.html">ORDER NOW</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="start">
            <p>Start your free, no-risk, 14 day trial! </p>
            <a href="pricing.html">Start Now!</a>
        </div>
    </div>
</div>

app/views/layouts/_showcase_activity.html.erb
<div id="showcase">
    <div class="container">
        <div class="section_header">
            <h3>Onze activiteiten</h3>
            <p> Hieronder een indruk van onze activiteiten </p>
        </div>            
        <div class="row feature_wrapper">
            <!-- Features Row -->
            <div class="features_op1_row">
                <!-- Feature -->
                <div class="span4 feature first">
                    <div class="img_box">
                        <a href="services.html">
                            <%= image_tag "service1.png" %>
                            <span class="circle"> 
                                <span class="plus">&#43;</span>
                            </span>
                        </a>
                    </div>
                    <div class="text">
                        <h6>Activiteit 1</h6>
                        <p>
                            Omschrijving
                        </p>
                    </div>
                </div>
                <!-- Feature -->
                <div class="span4 feature">
                    <div class="img_box">
                        <a href="services.html">
                            <%= image_tag "service2.png" %>
                            <span class="circle"> 
                                <span class="plus">&#43;</span>
                            </span>
                        </a>
                    </div>
                    <div class="text">
                        <h6>Activiteit 2</h6>
                        <p>
                            Omschrijving
                        </p>
                    </div>
                </div>
                <!-- Feature -->
                <div class="span4 feature last">
                    <div class="img_box">
                        <a href="services.html">
                            <%= image_tag "service3.png" %>
                            <span class="circle"> 
                                <span class="plus">&#43;</span>
                            </span>
                        </a>
                    </div>
                    <div class="text">
                        <h6>Activiteit 3</h6>
                        <p>
                            Omschrijving
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_showcase_projects.html.erb
<div id="showcase">
    <div class="container">
        <div class="section_header">
            <h3>Onze projecten</h3>
            <p> Hieronder een indruk van door ons gerealiseerde projecten </p>
        </div>            
        <div class="row feature_wrapper">
            <!-- Features Row -->
            <div class="features_op1_row">
                <!-- Feature -->
                <% projects = Project.where(:showcase => true) %>
                  <% projects.each_with_index do |project, i| %> 
                    <div class="span4 feature first %>">
                        <div class="img_box">
                            <%= link_to (image_tag project.image(:medium)), project_pictures_path(project) %>
                            <span class="circle"> 
                                <span class="plus">&#43;</span>
                            </span>
                        </div>
                        <div class="text">
                            <h6><%= project.title %></h6>
                            <p>
                                <%= project.description %>
                            </p>
                        </div>
                    </div>
                  <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ovec</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
   <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body class="pull_top">
    <%= render 'layouts/navbar' %>
    
    <% if current_page?(root_path) %>
      <%= render 'layouts/homepagebanner' %>
    <% end %>

    <% if current_page?(contact_path) %>
      <%= yield %>
    <% else %>
      <div class="container">
        <%= yield %>
      </div>
    <% end %>

    <%= render 'layouts/footer' %>

</body>
</html>